<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\eng\Versions.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>browser</SupportedOSPlatformVersion>
    <PackageId>SkiaMonoGameRendering.Kni.WebGL</PackageId>
    <Version>$(WebGlPackageVersion)</Version>
    <Description>GPU SkiaSharp to KNI Texture2D rendering for Blazor WebGL.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <RepositoryUrl>https://github.com/vchelaru/SkiaMonoGameRendering</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nkast.Xna.Framework.Graphics" Version="[$(KniVersion)]" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="[$(SkiaSharpVersion)]" />
    <PackageReference Include="SkiaSharp.Views.Blazor" Version="[$(SkiaSharpVersion)]" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\SkiaMonoGameRendering\SkiaBackend.cs" Link="Core\SkiaBackend.cs" />
    <Compile Include="..\SkiaMonoGameRendering\SkiaRenderer.cs" Link="Core\SkiaRenderer.cs" />
    <Compile Include="..\SkiaMonoGameRendering\SkiaTarget.cs" Link="Core\SkiaTarget.cs" />
    <Compile Include="..\SkiaMonoGameRendering\SkiaRenderTarget2D.cs" Link="Core\SkiaRenderTarget2D.cs" />
    <Compile Include="..\SkiaMonoGameRendering\SkiaSpriteBatchExtensions.cs" Link="Core\SkiaSpriteBatchExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
