<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <Import Project="..\..\eng\Versions.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <KniPlatform>BlazorGL</KniPlatform>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nkast.Kni.Platform.Blazor.GL" Version="$(KniVersion)" />
    <ProjectReference Include="..\..\src\SkiaGameRendering.Kni.WebGL\SkiaGameRendering.Kni.WebGL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.27" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="..\Shared\Scene.props" />
</Project>
