<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\external\fnalibs\FnaLibs.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\FNA\FNA.Core.csproj" />
    <ProjectReference Include="..\..\src\SkiaGameRendering.Fna.OGL\SkiaGameRendering.Fna.OGL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Sample.MonoGame.DesktopGL\Game1.cs" Link="Game1.cs" />
  </ItemGroup>
</Project>
